// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-aCeri-GnQllX2bFK8G9CLUv9pFRaHs',
    appId: '1:893790912854:web:fae95bfa6d19f99dd796f7',
    messagingSenderId: '893790912854',
    projectId: 'mylivetv-f582b',
    authDomain: 'mylivetv-f582b.firebaseapp.com',
    storageBucket: 'mylivetv-f582b.appspot.com',
    measurementId: 'G-JN6XLH3QQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYapz37g2VKhaTt032dfGdIvhqUXikiNU',
    appId: '1:893790912854:android:be72ed63d1c2b14ed796f7',
    messagingSenderId: '893790912854',
    projectId: 'mylivetv-f582b',
    storageBucket: 'mylivetv-f582b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgMQ-_bvVJ6iR8bYZuojcOV0GDSywvLY',
    appId: '1:893790912854:ios:1a70becfb98d397bd796f7',
    messagingSenderId: '893790912854',
    projectId: 'mylivetv-f582b',
    storageBucket: 'mylivetv-f582b.appspot.com',
    iosBundleId: 'com.example.mylivetv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgMQ-_bvVJ6iR8bYZuojcOV0GDSywvLY',
    appId: '1:893790912854:ios:1a70becfb98d397bd796f7',
    messagingSenderId: '893790912854',
    projectId: 'mylivetv-f582b',
    storageBucket: 'mylivetv-f582b.appspot.com',
    iosBundleId: 'com.example.mylivetv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb-aCeri-GnQllX2bFK8G9CLUv9pFRaHs',
    appId: '1:893790912854:web:7366612b46644d9cd796f7',
    messagingSenderId: '893790912854',
    projectId: 'mylivetv-f582b',
    authDomain: 'mylivetv-f582b.firebaseapp.com',
    storageBucket: 'mylivetv-f582b.appspot.com',
    measurementId: 'G-KG2YEFXWQB',
  );
}
